import numpy as np

# Tile codes
LAND = 0
WATER = 1
DIRT = 2
ROAD = 3

# ----------------------
# 8x8 tile pieces
# ----------------------



# /////////////Roads/////////////
# Top Right Road Corner
tile_road_top_right = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
])

# Top Right Road Corner (Reversed)
tile_road_top_right = np.array([
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
])

# Top Middle Road 
tile_road_top_middle = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
])

# Top Middle Road (Reverse)
tile_road_top_middle_reverse = np.array([
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Top Left Road Corner
tile_road_top_left = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
])

# Top Left Road Corner (Reverse)
tile_road_top_left_reverse = np.array([
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
])

# Middle Left Road
tile_road_middle_left = np.array([
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
])

# Middle Left Road (Reversed)
tile_road_middle_left_reverse = np.array([
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
])

# Middle Middle Road
tile_road_middle_middle = np.array([
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
])

# Middle Middle Road (Reversed)
tile_road_middle_middle_reverse = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Middle Right Road
tile_road_middle_right = np.array([
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
])

# Middle Right Road (Reverse)
tile_road_middle_right_reverse = np.array([
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
])
# Bottom Right Road Corner
tile_road_bottom_right = np.array([
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Right Road Corner (Reversed)
tile_road_bottom_right_reverse = np.array([
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
])

# Bottom Middle Road
tile_road_bottom_middle = np.array([
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bot Middle Road Reversed
tile_road_bottom_middle_reverse = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
])

# Bottom Left Road Corner
tile_road_bottom_right = np.array([
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, ROAD, ROAD, ROAD, ROAD],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Left Road Corner (Reversed)
tile_road_bottom_right_reverse = np.array([
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, LAND, LAND, LAND, LAND],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
    [ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD, ROAD],
])

# /////////////Water Tiles/////////////

# Top Right Water Corner
tile_water_top_right = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
])

# Top Right Water Corner (Reversed)
tile_water_top_right_reverse = np.array([
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
])

# Top Middle Water
tile_water_top_middle = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
])

# Top Middle Water (Reversed)
tile_water_top_middle_reverse = np.array([
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Top Left Water Corner
tile_water_top_left = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
])

# Top Left Water Corner (Reversed)
tile_water_top_left_reverse = np.array([
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
])

# Middle Left Water
tile_water_middle_left = np.array([
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
])

# Middle Left Water (Reversed)
tile_water_middle_left_reverse = np.array([
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
])

# Middle Middle Water
tile_water_middle_middle = np.array([
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
])

# Middle Middle Water (Reversed)
tile_water_middle_middle_reverse = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Middle Right Water
tile_water_middle_right = np.array([
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
])

# Middle Right Water (Reverse)
tile_water_middle_right_reverse = np.array([
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
])

# Bottom Right Water Corner
tile_water_bottom_right = np.array([
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Right Water Corner (Reversed)
tile_water_bottom_right_reverse = np.array([
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
])

# Bottom Middle Water
tile_water_bottom_middle = np.array([
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Middle Water (Reversed)
tile_water_bottom_middle_reverse = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
])

# Bottom Left Water Corner
tile_water_bottom_left = np.array([
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, WATER, WATER, WATER, WATER],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Left Water Corner (Reversed)
tile_water_bottom_left_reverse = np.array([
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, LAND, LAND, LAND, LAND],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
    [WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER],
])


# /////////////Dirt Tiles/////////////

# Top Right Dirt Corner
tile_dirt_top_right = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
])

# Top Right Dirt Corner (Reversed)
tile_dirt_top_right_reverse = np.array([
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
])

# Top Middle Dirt
tile_dirt_top_middle = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
])

# Top Middle Dirt (Reversed)
tile_dirt_top_middle_reverse = np.array([
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Top Left Dirt Corner
tile_dirt_top_left = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
])

# Top Left Dirt Corner (Reversed)
tile_dirt_top_left_reverse = np.array([
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
])

# Middle Left Dirt
tile_dirt_middle_left = np.array([
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
])

# Middle Left Dirt (Reversed)
tile_dirt_middle_left_reverse = np.array([
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
])

# Middle Middle Dirt
tile_dirt_middle_middle = np.array([
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
])

# Middle Middle Dirt (Reversed)
tile_dirt_middle_middle_reverse = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Middle Right Dirt
tile_dirt_middle_right = np.array([
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
])

# Middle Right Dirt (Reverse)
tile_dirt_middle_right_reverse = np.array([
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
])

# Bottom Right Dirt Corner
tile_dirt_bottom_right = np.array([
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Right Dirt Corner (Reversed)
tile_dirt_bottom_right_reverse = np.array([
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
])

# Bottom Middle Dirt
tile_dirt_bottom_middle = np.array([
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Middle Dirt (Reversed)
tile_dirt_bottom_middle_reverse = np.array([
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
])

# Bottom Left Dirt Corner
tile_dirt_bottom_left = np.array([
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, DIRT, DIRT, DIRT, DIRT],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
    [LAND, LAND, LAND, LAND, LAND, LAND, LAND, LAND],
])

# Bottom Left Dirt Corner (Reversed)
tile_dirt_bottom_left_reverse = np.array([
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, LAND, LAND, LAND, LAND],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
    [DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT],
])

